name: docker-cloud tests
on: [push]
defaults:
  run:
    working-directory: projects/docker-cloud
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "projects/docker-cloud/go.mod"
          cache-dependency-path: "projects/docker-cloud/go.sum"
          cache: true
      - name: Test
        run: make test
